<?php

namespace BackendBundle\Entity\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * ContentHashRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentHashRepository extends EntityRepository
{
    public function findByHash($hash)
    {
        if (!is_array($hash)) {
            $hash = [$hash];
        }

        return parent::findBy(['content_hash' => $hash]);
    }
}