services:
#    admin.example:
#        class: AdminBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
  admin.stats_collector:
    class: AdminBundle\Service\StatsCollector
    arguments: ["@backend.sharded_registry"]