#!/bin/bash
docker-compose build && docker-compose scale db=2 storage_node=2 && docker-compose up -d
sleep 1
docker exec docker_app_fpm_1 /home/app/console doctrine:database:create --connection=db_1
docker exec docker_app_fpm_1 /home/app/console doctrine:database:create --connection=db_2
docker exec docker_app_fpm_1 /home/app/console shardman:migrateall
docker exec docker_app_fpm_1 /home/app/console assetic:dump
docker exec docker_app_fpm_1 rm -rf /tmp/symfony-cache /tmp/symfony-logs /tmp/images